
package br.org.abrasf.nfse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotaFiscalServiceSoap", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotaFiscalServiceSoap {


    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://www.abrasf.org.br/nfse.xsd/RecepcionarLoteRps")
    @WebResult(name = "RecepcionarLoteRpsResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "RecepcionarLoteRps", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.RecepcionarLoteRps")
    @ResponseWrapper(localName = "RecepcionarLoteRpsResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.RecepcionarLoteRpsResponse")
    public String recepcionarLoteRps(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RecepcionarLoteRpsSincrono", action = "http://www.abrasf.org.br/nfse.xsd/RecepcionarLoteRpsSincrono")
    @WebResult(name = "RecepcionarLoteRpsSincronoResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "RecepcionarLoteRpsSincrono", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.RecepcionarLoteRpsSincrono")
    @ResponseWrapper(localName = "RecepcionarLoteRpsSincronoResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.RecepcionarLoteRpsSincronoResponse")
    public String recepcionarLoteRpsSincrono(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GerarNfse", action = "http://www.abrasf.org.br/nfse.xsd/GerarNfse")
    @WebResult(name = "GerarNfseResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "GerarNfse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.GerarNfse")
    @ResponseWrapper(localName = "GerarNfseResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.GerarNfseResponse")
    public String gerarNfse(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarNfse", action = "http://www.abrasf.org.br/nfse.xsd/CancelarNfse")
    @WebResult(name = "CancelarNfseResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "CancelarNfse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.CancelarNfse")
    @ResponseWrapper(localName = "CancelarNfseResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.CancelarNfseResponse")
    public String cancelarNfse(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SubstituirNfse", action = "http://www.abrasf.org.br/nfse.xsd/SubstituirNfse")
    @WebResult(name = "SubstituirNfseResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "SubstituirNfse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.SubstituirNfse")
    @ResponseWrapper(localName = "SubstituirNfseResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.SubstituirNfseResponse")
    public String substituirNfse(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://www.abrasf.org.br/nfse.xsd/ConsultarLoteRps")
    @WebResult(name = "ConsultarLoteRpsResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "ConsultarLoteRps", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarLoteRps")
    @ResponseWrapper(localName = "ConsultarLoteRpsResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarLoteRpsResponse")
    public String consultarLoteRps(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://www.abrasf.org.br/nfse.xsd/ConsultarNfsePorRps")
    @WebResult(name = "ConsultarNfsePorRpsResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "ConsultarNfsePorRps", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfsePorRps")
    @ResponseWrapper(localName = "ConsultarNfsePorRpsResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfsePorRpsResponse")
    public String consultarNfsePorRps(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseServicoPrestado", action = "http://www.abrasf.org.br/nfse.xsd/ConsultarNfseServicoPrestado")
    @WebResult(name = "ConsultarNfseServicoPrestadoResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "ConsultarNfseServicoPrestado", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseServicoPrestado")
    @ResponseWrapper(localName = "ConsultarNfseServicoPrestadoResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseServicoPrestadoResponse")
    public String consultarNfseServicoPrestado(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseServicoTomado", action = "http://www.abrasf.org.br/nfse.xsd/ConsultarNfseServicoTomado")
    @WebResult(name = "ConsultarNfseServicoTomadoResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "ConsultarNfseServicoTomado", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseServicoTomado")
    @ResponseWrapper(localName = "ConsultarNfseServicoTomadoResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseServicoTomadoResponse")
    public String consultarNfseServicoTomado(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

    /**
     * 
     * @param mensagemXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseFaixa", action = "http://www.abrasf.org.br/nfse.xsd/ConsultarNfseFaixa")
    @WebResult(name = "ConsultarNfseFaixaResult", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
    @RequestWrapper(localName = "ConsultarNfseFaixa", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseFaixa")
    @ResponseWrapper(localName = "ConsultarNfseFaixaResponse", targetNamespace = "http://www.abrasf.org.br/nfse.xsd", className = "br.org.abrasf.nfse.ConsultarNfseFaixaResponse")
    public String consultarNfseFaixa(
        @WebParam(name = "mensagemXML", targetNamespace = "http://www.abrasf.org.br/nfse.xsd")
        String mensagemXML);

}
